Document: webview
Title: Debian webview Manual
Author: <insert document author here>
Abstract: This manual describes what webview is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/webview/webview.sgml.gz

Format: postscript
Files: /usr/share/doc/webview/webview.ps.gz

Format: text
Files: /usr/share/doc/webview/webview.text.gz

Format: HTML
Index: /usr/share/doc/webview/html/index.html
Files: /usr/share/doc/webview/html/*.html

  
